spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

app:
  datasource:
    ds1:
      url: 'jdbc:mysql://localhost:3306/authorsdb?createDatabaseIfNotExist=true'
      username: root
      password: root
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 8
      minumum-idle: 8
      pool-name: MyPoolDS1
      connection-test-query: select 1 from dual
    ds2:
      url: 'jdbc:mysql://localhost:3306/booksdb?createDatabaseIfNotExist=true'
      username: root
      password: root
      connection-timeout: 50000
      idle-timeout: 300000
      max-lifetime: 900000
      maximum-pool-size: 8
      minumum-idle: 8
      pool-name: MyPoolDS2
      connection-test-query: select 1 from dual

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
